src/apps/dbpedialinks/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

app_name = 'dbpedialinks'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^letter/(?P<letter_bit>.*).html$', views.home, name='home_letter'),

    url(r'^entities$', views.entities, name='entities'),
    url(r'^entities/(?P<entity_id>\d+).html$',
        views.entities,
        name='entities_detail'),
    url(r'^graph_test/(?P<entity_id>\d+)$',
        views.graph_test,
        name='graph_test'),
    url(r'^graph_test_two_levels/(?P<entity_id>\d+)$',
        views.graph_test_two_levels,
        name='graph_test_two_levels'),
    url(r'^ajax/sg$', views.ajax_scigraph, name='ajax_scigraph'),
    url(r'^ajax/tags$', views.ajax_tags_info, name='ajax_tags_info'),
    url(r'^ajax/dbpedia$', views.ajax_dbpedia_info, name='ajax_dbpedia_info'),

    # not used:
    url(r'^articles$', views.articles, name='articles'),
    # url(r'^articles/(?P<article_id>\d+)$',
    # views.articles,
    # name='articles_detail'),
]

src/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

admin.site.site_header = 'Administration'
admin.site.site_title = 'dbpedialinks'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dbpedialinks.urls')),
    # url(r'^dbpedialinks/', include('dbpedialinks.urls')),
]

src/apps/dbpedialinks/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib import admin
from collections import Counter

import datetime
from django.conf import settings 
DEMO_MODE_FLAG = settings.DEMO_MODE_FLAG

# See also: https://docs.djangoproject.com/en/1.10/topics/migrations/#workflow



# =============================================================================
# UPDATE HERE TO REDUCE THE NUMBER OF SUBJECTS USED
# =============================================================================

class FilteredModelManager(models.Manager):
    """A custom model manager that filters out DBPediaEntity subjects with less than 2 articles.
    This ensures that we never generate too many pages when building a static dump of the site"""
    def get_queryset(self):
        if DEMO_MODE_FLAG:
            return super(FilteredModelManager, self).get_queryset().filter(totarticles__gt=10)
        else:
            return super(FilteredModelManager, self).get_queryset()




class SGDocument(models.Model):
    """Model definition for SGDocument."""

    title = models.CharField(
        max_length=250,
        verbose_name="title",
        null=True,
        blank=True,
    )
    uri = models.URLField(max_length=300)

    author = models.CharField(
        blank=True, max_length=200, verbose_name="author")
    pubyear = models.IntegerField(
        blank=True, null=True, verbose_name="publication year", help_text="")
    description = models.TextField(
        blank=True,
        verbose_name="description (put everything in here for now)")

    dbentities = models.ManyToManyField('DBPediaEntity')

    class Meta:
        """Meta definition for SGDocument."""

        verbose_name = 'SGDocument'
        verbose_name_plural = 'SGDocuments'
        ordering = ["uri"]

    def __unicode__(self):
        """Unicode representation of SGDocument."""
        return self.uri

    class Admin(admin.ModelAdmin):
        list_display = ('id', 'title', 'uri')
        search_fields = ['id', 'title', 'uri']




class DBPediaEntity(models.Model):
    """Model definition for DBPediaEntity."""

    title = models.CharField(
        max_length=250,
        verbose_name="title",
        null=True,
        blank=True,
    )
    uri = models.URLField(max_length=300)

    totarticles = models.IntegerField(
        null=True, blank=True, verbose_name="Tot associated articles")
    dbtype = models.CharField(
        blank=True, max_length=200, verbose_name="dbtype")
    description = models.TextField(
        blank=True,
        verbose_name="description (put everything in here for now)")
    top_rel_subjects = models.ManyToManyField(
        'self',
        through='Subject_Rel',
        symmetrical=False,
        # related_name="subject2",
        through_fields=('subject1', 'subject2'),
    )

    objects = FilteredModelManager()

    class Meta:
        """Meta definition for DBPediaEntity."""

        verbose_name = 'DBPedia Entity'
        verbose_name_plural = 'DBPedia Entities'
        ordering = ["title"]

    def __unicode__(self):
        """Unicode representation of DBPediaEntity."""
        return self.uri

    def update_tot_count(self):
        self.totarticles = self.sgdocument_set.count()
        self.save()

    # PS once calculated, used the <top_rel_subjects> method instead!
    def related_subjects(self, size=99999999, articles_set=None, CACHE=False):
        """
        Compute co-occurring subjects across whole publications; returns a list of tuples [(subj, count)] sorted by max count descencing

        NOTE this can be cached in the DB using the CACHE flag!  

        <articles_set> : allows to pass manually a queryset for extracting co-occurrence data
        """

        def count_and_reduce(lista, size):
            "reduce by taking first N elements sorted by tot count"
            c = Counter(lista)
            out = c.items()
            out = sorted(out, key=lambda t: (t[1], t[0].title), reverse=True)
            print(
                "Found:",
                len(out),
                "Keep:",
                size,
            )
            return out[:size]

        if not articles_set:
            articles_set = self.sgdocument_set.all()
        # approach 1: use co-occurrnce to define relatedness
        related = []
        for a in articles_set:
            related += a.dbentities.exclude(id=self.id)
        out = count_and_reduce(related, size)

        if CACHE:
            for this in out:
                print("Caching %s ... " % str(this))
                rel = Subject_Rel.objects.create(
                    subject1=self, subject2=this[0], score=this[1])

        # finally return a dict
        return out

    class Admin(admin.ModelAdmin):
        list_display = ('id', 'title', 'uri')
        search_fields = ['id', 'title', 'uri']


class Subject_Rel(models.Model):
    subject1 = models.ForeignKey(
        DBPediaEntity,
        on_delete=models.CASCADE,
        related_name="is_subject_in_relations")
    subject2 = models.ForeignKey(
        DBPediaEntity,
        on_delete=models.CASCADE,
        related_name="is_object_in_relations")
    score = models.IntegerField(null=True)

src/apps/dbpedialinks/views.py
#!/usr/bin/env python
# encoding: utf-8

from django.shortcuts import render, redirect, get_object_or_404
from django.utils.http import urlquote
from django.http import HttpResponse, HttpResponseNotFound
from django.db.models import Q

import string
from time import strftime
from collections import Counter, OrderedDict

import pyscigraph
import ontospy

from django.conf import settings 
DEMO_MODE_FLAG = settings.DEMO_MODE_FLAG

from render_block import render_block_to_string
from .models import *


class OrderedCounter(Counter, OrderedDict):
    pass


def home(request, letter_bit=None):
    """
    landing page

    TIPS:

    In [14]: import string

    In [15]: string.letters
    Out[15]: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'

    In [16]: string.ascii_letters
    Out[16]: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

    In [17]: string.ascii_lowercase
    Out[17]: 'abcdefghijklmnopqrstuvwxyz'

    In [18]: string.punctuation
    Out[18]: '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

    In [19]: string.printable
    Out[19]: '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'

    """

    letter = request.GET.get("letter", None)
    query = request.GET.get("query", None)

    # fix to allow proper URLs wget can extract
    if letter_bit:
        letter = letter_bit

    alphabet = string.ascii_lowercase
    alphabet = alphabet + "*"

    punctuation_and_numbers = string.punctuation + "1234567890"

    entities = []

    if letter:
        if letter == "*":
            filterList = list(punctuation_and_numbers)
            query = Q()
            for x in filterList:
                query = query | Q(title__istartswith=x)
                entities = DBPediaEntity.objects.filter(query)
            query = None  # zero it not to interfere with template logic
        else:
            entities = DBPediaEntity.objects.filter(title__istartswith=letter)

    elif query:
        entities = DBPediaEntity.objects.filter(title__icontains=query)

    context = {
        'articlestot': SGDocument.objects.count(),
        'entitiestot': DBPediaEntity.objects.count(),
        'entities': entities,
        'alphabet': alphabet,
        'thisletter': letter,
        'query': query,
        'DEMO_MODE_FLAG': DEMO_MODE_FLAG,
    }

    return render(request, 'dbpedialinks/home.html', context)


def entities(request, entity_id=None):
    """
    landing page + detail for entities
    """

    filters_id = request.GET.getlist("filters")
    context = {}

    entity = get_object_or_404(DBPediaEntity, pk=int(entity_id))

    subject = get_object_or_404(DBPediaEntity, pk=int(entity_id))
    filters = [subject]

    if filters_id:
        filters += [DBPediaEntity.objects.get(pk=int(x)) for x in filters_id]
        print("===== Filters: ", str(filters))
        articles = SGDocument.objects.filter()
        for el in filters:
            articles = articles.filter(dbentities=el)

    else:

        if DEMO_MODE_FLAG:
            articles = subject.sgdocument_set.all()[:50]
        else:
            articles = subject.sgdocument_set.all()

        #  create data for dataviz
        SIZE0, SIZE1, SIZE2 = 70, 50, 5
        green, lightgreen, yellow, lightorange, orange, red = 0, 0.4, 0.5, 0.6, 0.7, 0.8
        LVL0, LVL1, LVL2 = yellow, green, lightgreen  # templates uses this to determine color
        # LVL0, LVL1, LVL2 = orange, red, lightorange

        rels = entity.is_subject_in_relations.all(
        )  # NOTE requires cached objects! 2018-11-29
        LINKS = [(x.subject1, x.subject2) for x in rels]
        SEED = [(entity, SIZE0, LVL0)]
        NODES = [(x.subject2, SIZE1, LVL1)
                 for x in rels]  # change with x.score
        NODES_AND_SEED = NODES + SEED  # add home entity by default, PS score drives color
        for node in NODES:
            for x in node[0].is_subject_in_relations.all()[:5]:
                if x.subject2.id not in [n[0].id for n in NODES_AND_SEED]:
                    NODES_AND_SEED += [(x.subject2, SIZE2, LVL2)]
                LINKS += [(x.subject1, x.subject2)]

        context.update({'nodes': NODES_AND_SEED, 'links': LINKS})

    # CO-OCCURRING SUBJECTS
    sorted_related = subject.related_subjects(
        articles_set=articles)  # =>list of tuples (subject, count)
    filters_minus_entity = [f for f in filters if f.id != subject.id]

    context.update({
        'entity': subject,
        'filters': filters,
        'filters_minus_entity': filters_minus_entity,
        'articles': articles,
        'related_subjects': sorted_related,
        'DEMO_MODE_FLAG': DEMO_MODE_FLAG,
        # 'related_subjects_graph': sorted_related[:20]
    })

    return render(request, 'dbpedialinks/subject.html', context)


def ajax_tags_info(request):
    """
    Get tag info via ajax

    eg http://scigraph.springernature.com/things/articles/0786393400bb0690ffbbc208884e5271
    """

    sg_id = request.GET.get("id", None)
    print("ID DOCUMENT === ", sg_id)

    article = get_object_or_404(SGDocument, uri=sg_id)

    context = {
        'tags': article.dbentities.all(),
    }

    return_str = render_block_to_string(
        'dbpedialinks/snippet_ajax_tag_info.html', 'tag_info', context)

    return HttpResponse(return_str)


def ajax_dbpedia_info(request):
    """
    Get dbpedia description info via ajax

    eg http://dbpedia.org/resource/Panicum_virgatum
    """

    dbpedia_id = request.GET.get("id", None)
    if "/page/" in dbpedia_id:
        dbpedia_id = dbpedia_id.replace("/page/", "resource/")
    print("ID FOR DBPedia === ", dbpedia_id)

    # load ontospy without generating schema info, but pull out URI entity
    o = ontospy.Ontospy(dbpedia_id, build_all=False)
    e = o.build_entity_from_uri(dbpedia_id)
    if e:
        desc = e.bestDescription()
    else:
        desc = "Entity description not found"

    # context = {
    #     'desc' : desc,
    # }

    # return_str = render_block_to_string('dbpedialinks/snippet_ajax_tag_info.html',
    #                                     'tag_info',
    #                                     context)

    return HttpResponse(desc)


# ===========
# UNUSED AND TESTS
# ===========


def graph_test(request, entity_id=None):
    """
    based on http://bl.ocks.org/eyaler/10586116
    """

    filters_id = request.GET.getlist("filters")
    if entity_id:
        entity = get_object_or_404(DBPediaEntity, pk=int(entity_id))
        context = {
            'entity': entity,
            'related_subjects': entity.related_subjects(10),
        }
    else:
        context = {'entity': None}
    return render(request, 'dbpedialinks/test/graph_test.html', context)


def graph_test_two_levels(request, entity_id=None):
    """
    same as above but passing two levels worth of data to display a more interesting graph
    what changes is the data strucure we send back

    nodes = [list of unique nodes with score]
    links = [list of unique links tuple]
    """

    entity = get_object_or_404(DBPediaEntity, pk=int(entity_id))

    SIZE1 = 50  #testing fix sizes: reads well.. but less interesting in the long run
    SIZE2 = 5
    # requires new cached objects! 2018-11-29
    rels = entity.is_subject_in_relations.all()
    LINKS = [(x.subject1, x.subject2) for x in rels]
    SEED = [(entity, SIZE1)]
    NODES = [(x.subject2, x.score) for x in rels]
    NODES_AND_SEED = NODES + SEED  # add home entity by default, score drives color

    for node in NODES:
        for x in node[0].is_subject_in_relations.all()[:5]:
            if x.subject2.id not in [n[0].id for n in NODES_AND_SEED]:
                NODES_AND_SEED += [(x.subject2, x.score)]
            LINKS += [(x.subject1, x.subject2)]

    context = {'entity': entity, 'nodes': NODES_AND_SEED, 'links': LINKS}

    return render(request, 'dbpedialinks/test/graph_test.2.html', context)


def articles(request, article_id=None):
    """
    landing page + detail for articles
    """
    uri = request.GET.get("uri", None)

    if uri:

        # article = get_object_or_404(SGDocument, pk=int(article_id))
        article = get_object_or_404(SGDocument, uri=uri)

        context = {'article': article}

    else:
        context = {'article': None}

    return render(request, 'dbpedialinks/articles.html', context)


def ajax_scigraph(request):
    """
    Use SG API to get metadata

    eg http://scigraph.springernature.com/things/articles/0786393400bb0690ffbbc208884e5271
    """

    sg_id = request.GET.get("id", None)
    print("ID FOR SCIGRAPH === ", sg_id)

    cl = pyscigraph.SciGraphClient()
    e = cl.get_entity_from_id(uri=sg_id)

    if e:
        title = e.title
        doi = e.doi
        abstract = e.getValuesForProperty(
            "http://scigraph.springernature.com/ontologies/core/abstract")
        if abstract: abstract = abstract[0]

        context = {
            'article_id': sg_id,
            'title': title,
            'doi': doi,
            'abstract': abstract,
        }

        return_str = render_block_to_string(
            'dbpedialinks/snippet_ajax_article_info.html', 'article_info',
            context)

        return HttpResponse(return_str)

    else:
        return HttpResponse(
            "Sorry the request timed out - <a href='%s' target='_blank'>try on SciGraph?</a>"
            % sg_id)

src/apps/dbpedialinks/templates/dbpedialinks/articles.html
{% extends "dbpedialinks/base.html" %}
{% load commontags %}
{% load static %}

{% block navbar %}

    {% with thispage="home" %}

    {% include "dbpedialinks/default-navbar.html" %}

    {% endwith %}

{% endblock navbar %}


  {% block bodycontent %}


  <ol class="breadcrumb">
      <li><a href="{% url 'dbpedialinks:home' %}">Home</a></li>
      <li class="active">Article details</li>
    </ol>


    <div class="page-header">
      <h1>Article:
        {% if article %}
          <span class="text-default" style="font-size: 70%;">{{article.uri}}</span>
        {% endif %}
      </h1>
    </div>


    <div class="container">


    <div class="row">

      <div class="col-md-12" style="margin-top: 20px;">


        
        {% if article %}


        <h5 class="black">SciGraph URI</h5>
        <a href="{{article.uri}}" target="_blank">{{article.uri}}</a> <span class="text-muted">Click to view document details</span>
        
        <br /><br />
        <hr>

        <h5 class="black">Tagged with DBpedia Entities ({{article.dbentities.count}})</h5>
        <br />

        
        {% for a in article.dbentities.all %}
          <li style="-margin-top: 2px;">
            <a class="btn btn-xs btn-warning" href="{% url 'dbpedialinks:entities_detail' a.id %}"   title="View other articles tagged with this concept" >{{a.title}}</a> 

             &nbsp;<a class="btn btn-xs btn-default" href="{{a.uri}}" target="_blank"   >view on DBpedia</a> 
             &nbsp;<a class="btn btn-xs btn-default" href="https://en.wikipedia.org/wiki/{{a.uri|url_last_bit}}" target="_blank"   >view on WikiPedia</a> 
          
          </li> <br />
        {% endfor %}
          



          
        {% endif %}
          
          

       </div>

    </div>



    <div class="row">

      <hr>


    <div class="col-md-12">
       {# <hr class="-margin50"> #}


       <br />
       <p><b class="text-muted text-uppercase">Questions?</b></p>
       <p class="-lead">Ping us on our  <a href="https://hive.springernature.com/groups/knowledge-graph" target="_blank">Hive homepage</a>.</p>




      </div>


    </div>




    </div> <!-- /container -->


    <div class="container margin50">


    </div> <!-- /container -->


  {% endblock bodycontent %}

src/apps/dbpedialinks/templates/dbpedialinks/default-navbar.html
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'dbpedialinks:home' %}">
      <span class="glyphicon glyphicon-home" aria-hidden="true" style="font-size: 90%;"></span>&nbsp;&nbsp;{{navbar_title|default:"SciGraph 2 DBPedia links browser"}}
      </a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">

      </ul>



    </div><!--/.nav-collapse -->

  </div>
</nav>

src/apps/dbpedialinks/templates/dbpedialinks/ga.html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-T4B4FDV3TR"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-T4B4FDV3TR');
</script>

src/apps/dbpedialinks/templates/dbpedialinks/snippet_ajax_tag_info.html
{% load static %}
{% load commontags %}



{% block tag_info %}
    
    <b>Subjects:</b>&nbsp; 
    {% for a in tags %}

        <a class="btn btn-xs btn-primary" style="margin-bottom: 5px;" href="{% url 'dbpedialinks:entities_detail' a.id %}"   title="View other articles tagged with this concept" >{{a.title}}</a> 
        
    {% endfor %}
        

{% endblock tag_info %}
    

src/apps/dbpedialinks/templates/dbpedialinks/subject.html
{% extends "dbpedialinks/base.html" %} 
{% load commontags %} 
{% load static %} 

{% block navbar %} 
{% with thispage="home" %} 
{% include "dbpedialinks/default-navbar.html" %} 
{% endwith %} 
{% endblock navbar %} 


{% block bodycontent %}

<ol class="breadcrumb">
  <li>
    <a href="{% url 'dbpedialinks:home' %}">Home</a>
  </li>
  <li class="active">{{entity.title}}</li>
</ol>



<div class="container">


  <div class="row">




    <div class="col-md-12" style="margin-top: 20px;">

      <h5 class="text-muted">
        <span class="glyphicon glyphicon-tags" aria-hidden="true" style="font-size: 100%;"></span>&nbsp;&nbsp;Subject{{filters|pluralize}}:</h5>
      <h1>
        <span class="text-warning">{{entity.title}}</span>


        {% if filters_minus_entity %} 
          {% for f in filters_minus_entity %}
          &nbsp;+&nbsp;
          <a class="text-warning" style="font-size: 60%" href="{% url 'dbpedialinks:entities_detail' f.id %}" title="Click to focus on this subject">{{f.title}}</a>
          <a class="text-danger" style="font-size: 30%" href="{% url 'dbpedialinks:entities_detail' entity.id %}?{% for x in  filters_minus_entity %}{% if not f.id == x.id %}filters={{x.id}}&{% endif %}{% endfor %}" title="Remove subject from filters">remove</a>
          {% endfor %} 
        {% endif %}

        &nbsp;&nbsp;<a class="btn btn-xs btn-default" style="-margin-top: 15px;" href="{% url 'dbpedialinks:home' %}">New Search</a>


      </h1>
      <hr> 
      {% if not filters_minus_entity %}

          
          {% comment %}
             DISABLED - ajax call won't work with static site       
          <div id="subject_desc" class="text-muted">
            loading DBpedia info...
          </div>
          {% endcomment %}


          <a class="btn btn-xs btn-info" href="{{entity.uri}}" target="_blank">View on DBpedia</a>
          &nbsp;&nbsp;
          <a class="btn btn-xs btn-primary" href="https://en.wikipedia.org/wiki/{{entity.uri|url_last_bit}}" target="_blank">View on Wikipedia</a>

          <hr> 
      {% else %}
          <div class="text-muted">
          <small>Tip: click on one of the filters above to pivot your search</small>
          </div>
          <hr>
      {% endif %}


    </div>



  </div> 
  {% comment %} first row ends {% endcomment %}


  {% comment %} **** D3 CHART ***** {% endcomment %}

  {% if not filters_minus_entity %}
  <div class="row">

    <div class="col-md-12" style="margin-bottom: 30px;">

      <span class="text-muted">Top related subjects:</span>
      
      
      <div id="graph_div" class="-col-md-12" style="min-height: 500px; border: lightgray 0.1px solid; overflow: hidden;">       

      </div>
    
    </div>
  </div>
  <!-- /row -->
  {% endif %}

  <div class="row">

    <div class="col-md-4" style="margin-top: 30px;">


      <h5 class="text-muted">RELATED SUBJECTS:
      <br /><small class="text-muted">The publications listed also have these subjects</small>
      </h5>
      
        <hr>

      {% for k,v in related_subjects %} {% if not k in filters %}

      <a class="-btn -btn-xs -btn-primary high_contrast" style="margin-bottom: 5px; opacity: {{v|tagcloud_opacity}};"   
        {% if DEMO_MODE_FLAG %}
          href="{% url 'dbpedialinks:entities_detail' k.id %}"
        {% else %}
          href="{% url 'dbpedialinks:entities_detail' entity.id %}?filters={{k.id}}{% if filters_minus_entity %}{% for f  in  filters_minus_entity %}&filters={{f.id}}{% endfor %}{% endif %}"
        {% endif %}
       title="View other articles tagged with this concept">{{k.title}}</a>
      <span color="black;" style="opacity: {{v|tagcloud_opacity}};">&nbsp;{{v}} time{{v|pluralize}}</span>
      <br /> {% endif %} {% endfor %}



    </div>



    <div class="col-md-8" style="-margin-top: 20px;">

      <p class="lead text-muted" style="font-size: 160%;">Publications tagged with {{ filters|length|pluralize:"this,these" }} subject{{filters|pluralize}}:
        <span style="font-size: 150%; color: blue;">{{articles|length}}</span>
      </p>

      <p>
        <small class="text-muted">Note: {% if DEMO_MODE_FLAG %}Top 50 publications shown only. {% endif %}Open an item panel to view more info{% if articles|length < 31 %}&nbsp;<a href="javascript:megaLoad();">(open all)</a>{% endif %}</small>
      </p>

      <br />


      <div class="panel-group">
        {% for a in articles %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" class="text-warning" href="#{{a.uri|url_last_bit}}" style="font-size: 90%;" title="Open panel">
                {{forloop.counter}}. {{a.title}}
              </a> 
            </h4>
          </div>
          <div id="{{a.uri|url_last_bit}}" class="panel-collapse collapse ajax_pub_info_loaded">
            <div class="panel-body ">
              Year: {{a.pubyear}}
              <br />View: <a href="http://dx.doi.org/{{a.description}}" target="_blank" title="View Publication {{a.description}}">DOI: {{a.description}}</a> | <a target="_blank" href="https://scigraph.springernature.com/pub.{{a.description}}" title="View in SciGraph">scigraph record</a>
              <br />
            </div>
            <div class="panel-footer">

            
            {% if not DEMO_MODE_FLAG %}
              Subjects loading..
            {% endif %}
              

              

            </div>
          </div>
        </div>
        {% endfor %}
      </div>


    </div>

  </div>



</div>
<!-- /container -->


<div class="container margin50">


</div>
<!-- /container -->


{% endblock bodycontent %} {% block extrajs %}


<script>

  function ajax_load_pub_info(uri, dest) {
    $.get('{% url 'dbpedialinks:ajax_scigraph' %}',
      {
        id: uri //'http://scigraph.springernature.com/things/articles/0786393400bb0690ffbbc208884e5271'
      },
      function (data) {
        dest.html(data);
      });
  }


  function ajax_load_tag_info(uri, dest) {
    $.get('{% url 'dbpedialinks:ajax_tags_info' %}',
      {
        id: uri //'http://scigraph.springernature.com/things/articles/0786393400bb0690ffbbc208884e5271'
      },
      function (data) {
        dest.html(data);

      });
  }


  function ajax_load_dbpedia_info() {
    $.get('{% url 'dbpedialinks:ajax_dbpedia_info' %}',
      {
        id: '{{entity.uri}}'
      },
      function (data) {
        if (data) {
           $("#subject_desc").html(data);
        } else {
          $("#subject_desc").html("<i>No description returned by DBPedia</i>");
        }
       

      });
  }

  $(".panel-collapse").on("show.bs.collapse", function () {
    console.log("Loading..." + $(this).attr('id'));

    if (!$(this).hasClass('ajax_pub_info_loaded')) {
      article_id = $(this).attr('id');
      {% if not DEMO_MODE_FLAG %}
      $(this).children(".panel-body").html("loading...");
      {% endif %}
      dest = $(this).children(".panel-body")
      ajax_load_pub_info("http://scigraph.springernature.com/things/articles/" + article_id, dest);
      $(this).addClass('ajax_pub_info_loaded');
    }

    if (!$(this).hasClass('ajax_tags_loaded')) {
      article_id = $(this).attr('id');
      {% if not DEMO_MODE_FLAG %}
      $(this).children(".panel-footer").html("loading...");
      {% endif %}
      dest = $(this).children(".panel-footer")
      ajax_load_tag_info("http://scigraph.springernature.com/things/articles/" + article_id, dest);
      $(this).addClass('ajax_tags_loaded');
    }

  });



  {% if not DEMO_MODE_FLAG and not filters_minus_entity %}
    $(function () {
      ajax_load_dbpedia_info();
    });
  {% endif %}


  function megaLoad() {
    $(".panel-collapse").collapse();
  }

</script> 



{% if not filters_minus_entity %}

  {% comment %} JS for D3 Graph {% endcomment %}

   {% include 'dbpedialinks/snippet_graph.html' %}

{% endif %}
  
  

{% endblock extrajs %}